CREATE TABLE HISTORICOS (
    ID_HIS NUMERIC(4) NOT NULL,
    DES_HIS VARCHAR(30) NOT NULL,
	CONSTRAINT  PK_ID_HIS PRIMARY KEY(ID_HIS)
);

CREATE TABLE AGENCIAS (
    NUM_AGE NUMERIC(5) NOT NULL,
    NOME_AGE VARCHAR(30) NOT NULL,
    ENDE_AGE VARCHAR(50) NOT NULL,
    NUM_AGE_ENDE VARCHAR(8),
    COMPL_AGE VARCHAR(20),
    BAIR_AGE VARCHAR(20),
    CIDA_AGE VARCHAR(30) NOT NULL,
    UF_AGE CHAR(2) NOT NULL,
    CEP_AGE CHAR(8) NOT NULL,
    FONE_AGE VARCHAR(13),
	CONSTRAINT PK_NUM_AGE PRIMARY KEY(NUM_AGE)
);
 
CREATE TABLE CLIENTES (
    ID_CLI NUMERIC(9) NOT NULL,
    NOME_CLI VARCHAR(50) NOT NULL,
    ENDE_CLI VARCHAR(50) NOT NULL,
    NUM_CLI INT,
    COMPL_CLI VARCHAR(20),
    BAIR_CLI VARCHAR(20),
    CIDA_CLI VARCHAR(30) NOT NULL,
    UF_CLI CHAR(2) NOT NULL,
    CEP_CLI CHAR(8) NOT NULL,
    FONE_CLI VARCHAR(13),
    CPF_CLI CHAR(11),
    DATA_NASC DATETIME,
    CNPJ CHAR(14),
	CONSTRAINT PK_ID_CLI PRIMARY KEY(ID_CLI)
);
 
CREATE TABLE CONTA_CORRENTE (
    NUM_AGE NUMERIC(5) NOT NULL,
    NUM_CC NUMERIC(10) NOT NULL,
    ID_CLI NUMERIC(9) NOT NULL,
    SALDO DECIMAL(15,2),
	PRIMARY KEY(NUM_AGE, NUM_CC), 
    CONSTRAINT FK_NUM_AGE FOREIGN KEY (NUM_AGE) REFERENCES AGENCIAS(NUM_AGE),
    CONSTRAINT FK_ID_CLI FOREIGN KEY (ID_CLI) REFERENCES CLIENTES(ID_CLI)
);
 
CREATE TABLE MOVIMENTACAO (
    NUM_AGE NUMERIC(5) NOT NULL,
    NUM_CC NUMERIC(10) NOT NULL,
    DATA_MOV DATETIME NOT NULL,
    NUM_DOCTO VARCHAR(6) NOT NULL,
    DEBITO_CREDITO CHAR(1),
    ID_HIS NUMERIC(4) NOT NULL,
    COMPL_HIS VARCHAR(30),
    VALOR DECIMAL(9,2),
	PRIMARY KEY (NUM_AGE, NUM_CC, DATA_MOV, NUM_DOCTO),
    CONSTRAINT FK_NUM_AGE FOREIGN KEY (NUM_AGE) REFERENCES AGENCIAS(NUM_AGE),
	CONSTRAINT FK_MOVIMENTACAO_CC FOREIGN KEY (NUM_AGE,NUM_CC) REFERENCES CONTA_CORRENTE(NUM_AGE,NUM_CC),
    CONSTRAINT FK_ID_HIS FOREIGN KEY (ID_HIS) REFERENCES HISTORICOS(ID_HIS)
);
 
CREATE TABLE USUARIOS (
    ID VARCHAR(20) NOT NULL,
    SENHAS VARCHAR(20) NOT NULL,
    NUM_AGE NUMERIC(5) NOT NULL,
	NUM_CC NUMERIC(10) NOT NULL,
	CONSTRAINT PK_ID PRIMARY KEY(ID),
	CONSTRAINT FK_USUARIOS_CC FOREIGN KEY (NUM_AGE,NUM_CC) REFERENCES CONTA_CORRENTE(NUM_AGE,NUM_CC)
 )