/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

/**
 *
 * @author Alunos
 */
public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    public menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu5 = new javax.swing.JMenu();
        jMenu6 = new javax.swing.JMenu();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        cadClientes = new javax.swing.JMenuItem();
        alterarAgencia = new javax.swing.JMenuItem();
        excuirClientes = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        cadAgencias = new javax.swing.JMenuItem();
        alterarAgencias = new javax.swing.JMenuItem();
        excluirAgencias = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        cadContaCorrente = new javax.swing.JMenuItem();
        alterarContaCorrente = new javax.swing.JMenuItem();
        excluirContaCorrente = new javax.swing.JMenuItem();
        jMenu7 = new javax.swing.JMenu();
        cadHistorico = new javax.swing.JMenuItem();
        alterarHistorico = new javax.swing.JMenuItem();
        excluirHistorico = new javax.swing.JMenuItem();
        jMenu8 = new javax.swing.JMenu();
        cadMovimentacao = new javax.swing.JMenuItem();
        alterarMovimentacao = new javax.swing.JMenuItem();
        excluirMovimentacao = new javax.swing.JMenuItem();
        jMenu9 = new javax.swing.JMenu();
        cadUsuario = new javax.swing.JMenuItem();
        alterarUsuario = new javax.swing.JMenuItem();
        excluirUsuario = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        jMenu5.setText("File");
        jMenuBar2.add(jMenu5);

        jMenu6.setText("Edit");
        jMenuBar2.add(jMenu6);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Clientes");

        cadClientes.setText("Cadastrar");
        cadClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadClientesActionPerformed(evt);
            }
        });
        jMenu1.add(cadClientes);

        alterarAgencia.setText("Alterar");
        alterarAgencia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarAgenciaActionPerformed(evt);
            }
        });
        jMenu1.add(alterarAgencia);

        excuirClientes.setText("Excluir");
        excuirClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excuirClientesActionPerformed(evt);
            }
        });
        jMenu1.add(excuirClientes);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Agências");

        cadAgencias.setText("Cadastrar");
        cadAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadAgenciasActionPerformed(evt);
            }
        });
        jMenu2.add(cadAgencias);

        alterarAgencias.setText("Alterar");
        alterarAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarAgenciasActionPerformed(evt);
            }
        });
        jMenu2.add(alterarAgencias);

        excluirAgencias.setText("Excluir");
        excluirAgencias.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirAgenciasActionPerformed(evt);
            }
        });
        jMenu2.add(excluirAgencias);

        jMenuBar1.add(jMenu2);

        jMenu4.setText("Conta Corrente");

        cadContaCorrente.setText("Cadastrar");
        cadContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadContaCorrenteActionPerformed(evt);
            }
        });
        jMenu4.add(cadContaCorrente);

        alterarContaCorrente.setText("Alterar");
        alterarContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarContaCorrenteActionPerformed(evt);
            }
        });
        jMenu4.add(alterarContaCorrente);

        excluirContaCorrente.setText("Excluir");
        excluirContaCorrente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirContaCorrenteActionPerformed(evt);
            }
        });
        jMenu4.add(excluirContaCorrente);

        jMenuBar1.add(jMenu4);

        jMenu7.setText("Histórico");

        cadHistorico.setText("Cadastrar");
        cadHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadHistoricoActionPerformed(evt);
            }
        });
        jMenu7.add(cadHistorico);

        alterarHistorico.setText("Alterar");
        alterarHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarHistoricoActionPerformed(evt);
            }
        });
        jMenu7.add(alterarHistorico);

        excluirHistorico.setText("Excluir");
        excluirHistorico.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirHistoricoActionPerformed(evt);
            }
        });
        jMenu7.add(excluirHistorico);

        jMenuBar1.add(jMenu7);

        jMenu8.setText("Movimentação");

        cadMovimentacao.setText("Cadastrar");
        cadMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadMovimentacaoActionPerformed(evt);
            }
        });
        jMenu8.add(cadMovimentacao);

        alterarMovimentacao.setText("Alterar");
        alterarMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarMovimentacaoActionPerformed(evt);
            }
        });
        jMenu8.add(alterarMovimentacao);

        excluirMovimentacao.setText("Excluir");
        excluirMovimentacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirMovimentacaoActionPerformed(evt);
            }
        });
        jMenu8.add(excluirMovimentacao);

        jMenuBar1.add(jMenu8);

        jMenu9.setText("Usuários");

        cadUsuario.setText("Cadastrar");
        cadUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cadUsuarioActionPerformed(evt);
            }
        });
        jMenu9.add(cadUsuario);

        alterarUsuario.setText("Alterar");
        alterarUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alterarUsuarioActionPerformed(evt);
            }
        });
        jMenu9.add(alterarUsuario);

        excluirUsuario.setText("Excluir");
        excluirUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                excluirUsuarioActionPerformed(evt);
            }
        });
        jMenu9.add(excluirUsuario);

        jMenuBar1.add(jMenu9);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 547, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cadClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadClientesActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        Cad_Cliente cadCliente = new Cad_Cliente(operacao);
        cadCliente.setVisible(true);
    }//GEN-LAST:event_cadClientesActionPerformed

    private void cadAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadAgenciasActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        Cad_Agencia cadAgencia = new Cad_Agencia(operacao);
        cadAgencia.setVisible(true);
    }//GEN-LAST:event_cadAgenciasActionPerformed

    private void cadHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadHistoricoActionPerformed
            // TODO add your handling code here:
        String operacao = "Incluir";
        Cad_Historico cadHistorico = new Cad_Historico(operacao);
        cadHistorico.setVisible(true);
    }//GEN-LAST:event_cadHistoricoActionPerformed

    private void cadContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadContaCorrenteActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        Cad_Conta_Corrente cadContaCorrente = new Cad_Conta_Corrente(operacao);
        cadContaCorrente.setVisible(true);
    }//GEN-LAST:event_cadContaCorrenteActionPerformed

    private void cadMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadMovimentacaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        Cad_Movimentacao cadMovimentacao = new Cad_Movimentacao(operacao);
        cadMovimentacao.setVisible(true);
    }//GEN-LAST:event_cadMovimentacaoActionPerformed

    private void cadUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cadUsuarioActionPerformed
        // TODO add your handling code here:
        String operacao = "Incluir";
        Cad_Usuario cadUsuario = new Cad_Usuario(operacao);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_cadUsuarioActionPerformed

    private void alterarAgenciaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarAgenciaActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        Cad_Cliente acesso_cliente = new Cad_Cliente(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_alterarAgenciaActionPerformed

    private void alterarAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarAgenciasActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        Cad_Agencia acesso_agencia = new Cad_Agencia(operacao);
        acesso_agencia.setVisible(true);
    }//GEN-LAST:event_alterarAgenciasActionPerformed

    private void excluirAgenciasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirAgenciasActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        Cad_Agencia acesso_agencia = new Cad_Agencia(operacao);
        acesso_agencia.setVisible(true);
    }//GEN-LAST:event_excluirAgenciasActionPerformed

    private void excuirClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excuirClientesActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        Cad_Cliente acesso_cliente = new Cad_Cliente(operacao);
        acesso_cliente.setVisible(true);
    }//GEN-LAST:event_excuirClientesActionPerformed

    private void excluirContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirContaCorrenteActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        Cad_Conta_Corrente acesso_conta_corrente = new Cad_Conta_Corrente(operacao);
        acesso_conta_corrente.setVisible(true);
    }//GEN-LAST:event_excluirContaCorrenteActionPerformed

    private void alterarContaCorrenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarContaCorrenteActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        Cad_Historico cadHistorico = new Cad_Historico(operacao);
        cadHistorico.setVisible(true);
    }//GEN-LAST:event_alterarContaCorrenteActionPerformed

    private void alterarHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarHistoricoActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        Cad_Historico cadHistorico = new Cad_Historico(operacao);
        cadHistorico.setVisible(true);
    }//GEN-LAST:event_alterarHistoricoActionPerformed

    private void excluirHistoricoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirHistoricoActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        Cad_Historico cadHistorico = new Cad_Historico(operacao);
        cadHistorico.setVisible(true);
    }//GEN-LAST:event_excluirHistoricoActionPerformed

    private void alterarMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarMovimentacaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        Cad_Movimentacao cadMovimentacao = new Cad_Movimentacao(operacao);
        cadMovimentacao.setVisible(true);
    }//GEN-LAST:event_alterarMovimentacaoActionPerformed

    private void excluirMovimentacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirMovimentacaoActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        Cad_Movimentacao cadMovimentacao = new Cad_Movimentacao(operacao);
        cadMovimentacao.setVisible(true);
    }//GEN-LAST:event_excluirMovimentacaoActionPerformed

    private void alterarUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alterarUsuarioActionPerformed
        // TODO add your handling code here:
        String operacao = "Alterar";
        Cad_Usuario cadUsuario = new Cad_Usuario(operacao);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_alterarUsuarioActionPerformed

    private void excluirUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_excluirUsuarioActionPerformed
        // TODO add your handling code here:
        String operacao = "Excluir";
        Cad_Usuario cadUsuario = new Cad_Usuario(operacao);
        cadUsuario.setVisible(true);
    }//GEN-LAST:event_excluirUsuarioActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem alterarAgencia;
    private javax.swing.JMenuItem alterarAgencias;
    private javax.swing.JMenuItem alterarContaCorrente;
    private javax.swing.JMenuItem alterarHistorico;
    private javax.swing.JMenuItem alterarMovimentacao;
    private javax.swing.JMenuItem alterarUsuario;
    private javax.swing.JMenuItem cadAgencias;
    private javax.swing.JMenuItem cadClientes;
    private javax.swing.JMenuItem cadContaCorrente;
    private javax.swing.JMenuItem cadHistorico;
    private javax.swing.JMenuItem cadMovimentacao;
    private javax.swing.JMenuItem cadUsuario;
    private javax.swing.JMenuItem excluirAgencias;
    private javax.swing.JMenuItem excluirContaCorrente;
    private javax.swing.JMenuItem excluirHistorico;
    private javax.swing.JMenuItem excluirMovimentacao;
    private javax.swing.JMenuItem excluirUsuario;
    private javax.swing.JMenuItem excuirClientes;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenu jMenu7;
    private javax.swing.JMenu jMenu8;
    private javax.swing.JMenu jMenu9;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuBar jMenuBar2;
    // End of variables declaration//GEN-END:variables
}
